name: wx-2026

services:
  postgres:
    image: postgres:15-alpine
    container_name: wx-refonte-site-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wx-refonte-site-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  strapi:
    build:
      context: ./strapi
      dockerfile: Dockerfile
    container_name: wx-refonte-site-strapi
    restart: unless-stopped
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: ${POSTGRES_DB}
      DATABASE_USERNAME: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_SSL:  ${DATABASE_SSL}
      HOST: 0.0.0.0
      PORT: 1337
      NODE_ENV: production
      STRAPI_DISABLE_TELEMETRY: ${STRAPI_DISABLE_TELEMETRY}
      SEED_DB: ${SEED_DB}
    depends_on:
      postgres:
        condition: service_healthy
    # NE PAS MONTER DE VOLUME SUR /opt/app/public
    # Strapi doit gérer ce dossier lui-même pour l'import
    volumes:
      - strapi_uploads:/opt/app/public/uploads
    networks:
      - wx-refonte-site-network
      - traefik-platform-network
    # ports:
    #   - "${STRAPI_PORT}:1337"
    expose:
      - 1337

    # Treafik labels for reverse proxy
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.wx-refonte-site-strapi.rule=Host(`${STRAPI_HOST}`)"
    #   - "traefik.http.routers.wx-refonte-site-strapi.entrypoints=websecure"
    #   - "traefik.http.routers.wx-refonte-site-strapi.tls=true"
    #   - "traefik.http.services.wx-refonte-site-strapi.loadbalancer.server.port=1337"

    labels:
      - "traefik.enable=true"

      # Router
      - "traefik.http.routers.wx-refonte-site-strapi.rule=Host(`preprod.webtinix.com`)"
      - "traefik.http.routers.wx-refonte-site-strapi.entrypoints=websecure"
      - "traefik.http.routers.wx-refonte-site-strapi.tls.certresolver=le"

      # Service
      - "traefik.http.services.wx-refonte-site-strapi.loadbalancer.server.port=1337"

      # Sécurité
      - "traefik.http.middlewares.wx-refonte-site-strapi-secure.headers.sslredirect=true"
      - "traefik.http.middlewares.wx-refonte-site-strapi-secure.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.wx-refonte-site-strapi-secure.headers.stsIncludeSubdomains=true"

      - "traefik.http.routers.wx-refonte-site-strapi.middlewares=wx-refonte-site-strapi-secure"

  nextjs:
    build:
      context: ./next
      dockerfile: Dockerfile
    container_name: wx-refonte-site-nextjs
    restart: unless-stopped
    environment:
      # Mettre à jour les variables du projet Next.js si nécessaire
      # NEXT_PUBLIC_API_URL: http://${STRAPI_HOST}:${STRAPI_PORT}
      STRAPI_URL: http://${STRAPI_HOST}:${STRAPI_PORT}
      NODE_ENV: production
    depends_on:
      - strapi
    networks:
      - wx-refonte-site-network
      - traefik-platform-network

    # ports:
    #   - "${NEXTJS_PORT}:3000"

    expose:
      - 3000

    labels:
      - "traefik.enable=true"

      # Router
      - "traefik.http.routers.wx-refonte-site-api.rule=Host(`preprod-api.webtinix.com`)"
      - "traefik.http.routers.wx-refonte-site-api.entrypoints=websecure"
      - "traefik.http.routers.wx-refonte-site-api.tls.certresolver=le"

      # Service
      - "traefik.http.services.wx-refonte-site-api.loadbalancer.server.port=3000"

      # Sécurité
      - "traefik.http.middlewares.wx-refonte-site-api-secure.headers.sslredirect=true"
      - "traefik.http.middlewares.wx-refonte-site-api-secure.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.wx-refonte-site-api-secure.headers.stsIncludeSubdomains=true"

      - "traefik.http.routers.wx-refonte-site-api.middlewares=wx-refonte-site-api-secure"

volumes:
  postgres_data:
  strapi_uploads: # Commenté car on ne l'utilise plus pour le moment

networks:
  wx-refonte-site-network:
    driver: bridge
  traefik-platform-network:
    external: true
